nitishtest/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from basecamp import views as basecamp_views


urlpatterns = [
    url(r'^$', basecamp_views.connect_basecamp, name='connect_basecamp'),
    url(r'^basecamp/get-access-token/$', basecamp_views.get_access_token, name='get_access_token'),
    url(r'^basecamp/get-code/$', basecamp_views.get_verification_code, name='get_verification_code'),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basecamp/models.py
from django.db import models

# Create your models here.

basecamp/forms.py
from django import forms


class ConnectBasecampForm(forms.Form):
    access_token = forms.CharField(widget=forms.TextInput(attrs={'class':'input-text','placeholder':'Access Token(Optional)'}), required=False, max_length=500)
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'input-text','placeholder':'Title'}), max_length=300)
    attachment = forms.FileField()


class BasecampAccessTokenForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={'class':'input-text','placeholder':'Verification Code'}), max_length=30)

basecamp/views.py
import json
import requests

from django.shortcuts import render
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.conf import settings
from django.shortcuts import render

from basecamp.forms import ConnectBasecampForm, BasecampAccessTokenForm
from basecamp.basecampapi import ConnectBasecamp


def connect_basecamp(request):
    context = {
        'form': ConnectBasecampForm()
    }

    if request.method == 'POST':
        form = ConnectBasecampForm(request.POST, request.FILES)

        if form.is_valid():
            if request.POST.get('access_token', ''):
                access_token = request.POST.get('access_token', '')
            else:
                access_token = settings.BASECAMP_ACCESS_TOKEN

            basecamp_obj = ConnectBasecamp(access_token)
            response = basecamp_obj.create_todo(request.POST.get('title', ''), request.FILES.get('attachment', ''))

            if response.status_code == 201:
                context.update({'success': True})
            else:
                context.update({'failure': True})

    return render(request, 'connect_basecamp.html', context)


def get_verification_code(request):
    code_url = "%s?client_id=%s&redirect_uri=%s&type=%s" % (
        settings.BASECAMP_AUTHORIZATION_URI,
        settings.BASECAMP_CLIENT_ID,
        settings.BASECAMP_REDIRECT_URI,
        settings.BASECAMP_TYPE
    )

    return HttpResponseRedirect(code_url)


def get_access_token(request):
    context = {
        'form': BasecampAccessTokenForm()
    }

    if request.method == 'POST':
        form = BasecampAccessTokenForm(request.POST)

        if form.is_valid():
            url = "%s?code=%s&client_id=%s&client_secret=%s&redirect_uri=%s&type=%s" % (
                settings.BASECAMP_ACCESS_TOKEN_URI,
                request.POST['code'],
                settings.BASECAMP_CLIENT_ID,
                settings.BASECAMP_CLIENT_SECRET,
                settings.BASECAMP_REDIRECT_URI,
                settings.BASECAMP_TYPE
            )

            response = requests.post(url)
            data = json.loads(response.text)
            if response.status_code == 200:
                access_token = data['access_token']
                context.update({'access_token': access_token})
            else:
                api_error = data
                context.update({'api_error': api_error})
        else:
            context['form'] = form

    return render(request, 'get_access_token.html', context)

basecamp/templates/base.html
{% load static %}

<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>
        <title>{% block title %}{% endblock %}</title>

        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    </head>
    <body>

        <nav class="navbar bg-primary">
            <a class="navbar-brand" href="/">
                Nitish Self Decode Test Assignment
            </a>
        </nav>

        {% block content %}{% endblock %}

        <footer>
            <p class="copyright text-center">
                &copy; 2017, Nitish Self Decode Test Assignment
            </p>
        </footer>

        <!-- *** SCRIPTS TO INCLUDE ***
        _________________________________________________________ -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <script>
            window.EForm = {
                validateForm: function() {
                    var self = this;
                    self.form = $('#dForm');

                    $(self.form[0].elements).each(function() {
                        $(this).removeAttr('required')
                    })

                    $('#id_title').on('blur', function() {
                        if(hasError(this)) {
                            $(this).closest('.form-group').addClass('has-error');
                        } else {
                            $(this).closest('.form-group').removeClass('has-error');
                        }
                    })

                    self.form.on('submit', function(e) {
                        var errors = 0;
                        $(self.form[0].elements).each(function() {
                            if(this.nodeName === 'INPUT' && (this.type === 'file' || this.type === 'text') && $(this).attr('id') != 'id_access_token') {
                                if($(this).val() === '') {
                                    $(this).closest('.form-group').addClass('has-error');
                                    errors += 1;
                                } else {
                                    $(this).closest('.form-group').removeClass('has-error')
                                }
                            }
                        });
                        if(errors) {
                            e.preventDefault();
                        }
                    });

                    $('#id_attachment').on('change', function() {
                        if(!this.files.length) return;
                        $('#fileName').text(this.files[0].name);
                        $(this).closest('.form-group').removeClass('has-error');
                    })

                    function hasError(field) {
                        if($(field).val() === '') return true;
                        return false;
                    }
                },
                init: function() {
                    this.validateForm()
                }
            }

            EForm.init();
        </script>

    </body>
</html>

basecamp/templates/connect_basecamp.html
{% extends "base.html" %}

{% block title %}Create TODO{% endblock %}

{% block content %}
    <section class="section intro align-items-center">
        <div class="col hidden-xs-down" style="max-width: 250px"></div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    {% if success %}
                        <div class="alert alert-success mt-3" style="padding:0.25rem 1.25rem;">
                            <small>TODO Created successfully!</small>
                        </div>
                    {% endif %}
                    {% if failure %}
                        <div class="alert alert-danger mt-3" style="padding:0.25rem 1.25rem;">
                            <small>There is some problem while connecting to basecamp API!</small>
                        </div>
                    {% endif %}
                    <form class="fm-container" id="dForm" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <label for="id_access_token">Access Token</label>
                                </div>
                                <div class="col text-right" style="font-size:12px;">
                                    <a role="button" target="_blank" href="{% url 'get_access_token' %}">Get Access Token</a>
                                </div>
                            </div>
                            {{ form.access_token }}
                            <div class="alert alert-info mt-3" style="padding:0.25rem 1.25rem;">
                                <small>If you want to regenerate the access token, Please click on the link and generate access token and provide it in input field. Provided access token will take priority over the access token used in application.</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_title">Title</label>
                            {{ form.title }}
                            <div class="fm-error">Title is required</div>
                        </div>
                        <div class="form-group">
                            <label for="">Attachment</label>
                            <label for="id_attachment" class="btn btn-outline-dark btn-sm mb-0" role="button">
                                Choose File
                                {{ form.attachment }}
                            </label>
                            <span id="fileName" class="ml-2"></span>
                            <div class="fm-error">File attachment is required</div>
                        </div>
                        <div class="text-center">
                            <input type="submit" class="btn btn-primary mt-2" style="width: 200px" role="button">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col hidden-xs-down" style="max-width: 250px"></div>
    </section>
{% endblock %}

basecamp/templates/get_access_token.html
{% extends "base.html" %}

{% block title %}Create TODO{% endblock %}

{% block content %}
    <section class="section intro align-items-center">
        <div class="col hidden-xs-down" style="max-width: 250px"></div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form class="fm-container" id="dForm" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <label for="id_title">Code</label>
                                </div>
                                <div class="col text-right" style="font-size:12px;">
                                    <a role="button" target="_blank" href="{% url 'get_verification_code' %}">Get Verification Code</a>
                                </div>
                            </div>
                            {{ form.code }}
                            {% if access_token %}
                                <div class="alert alert-info mt-3" style="padding:0.25rem 1.25rem;">
                                    <small>{{ access_token }}</small>
                                </div>
                            {% endif %}
                            {% if api_error %}
                                <div class="alert alert-danger mt-3" style="padding:0.25rem 1.25rem;">
                                    <small>{{ api_error }}</small>
                                </div>
                            {% endif %}
                        </div>
                        <div class="text-center">
                            <input type="submit" class="btn btn-primary mt-2" role="button" value="Get Access Token">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col hidden-xs-down" style="max-width: 250px"></div>
    </section>
{% endblock %}